### PR TITLE
fix #4

### LINKED ISSUE #4: in `1.1.0`, the metrics are not shared
When one creates more than one `PrometheusProducer` with default (or one global) prefix, then there is an exception on second such producer, like:
```
Exception in thread "main" java.lang.IllegalArgumentException: Collector already registered that provides name: skafka_producer_latency_count
	at io.prometheus.client.CollectorRegistry.register(CollectorRegistry.java:54)
	at io.prometheus.client.SimpleCollector$Builder.register(SimpleCollector.java:246)
	at com.evolutiongaming.skafka.producer.PrometheusProducer$.apply(PrometheusProducer.scala:27)
```

It would be better, if metrics would get initialized at `PrometheusProducer` level, not repeatedly for each newly created Producer.
As consequence - have to discard `prefix` argument - `skafka_producer` could be internally hardcoded value.

### PR DESCRIPTION
**Pull request by mr-git**
"lazy" init of metrics upon declaration of producers

### CODE REVIEW

File: modules/prometheus/src/main/scala/com/evolutiongaming/skafka/producer/PrometheusProducer.scala [hunk 1]
```diff
@@ -5,80 +5,99 @@ import com.evolutiongaming.skafka.ToBytes
...
-  def apply(
-    producer: Producer,
-    registry: CollectorRegistry,
-    prefix: String = "skafka_producer",
-    label: String = "skafka"): Producer = {
+  private var collectors: Collectors = _
 
-    implicit val ec = CurrentThreadExecutionContext
+  private def registerCollectors(registry: CollectorRegistry): Unit = synchronized {
+    if (collectors == null)
```
Comment (t3hnar) [inline modules/prometheus/src/main/scala/com/evolutiongaming/skafka/producer/PrometheusProducer.scala]: can we use Option ?

Comment (t3hnar) [reply modules/prometheus/src/main/scala/com/evolutiongaming/skafka/producer/PrometheusProducer.scala]: actually I'm going to merge and improve that part
